-- MySQL Script generated by MySQL Workbench
-- 10/27/15 20:28:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rockpaperscissor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rockpaperscissor` ;

-- -----------------------------------------------------
-- Schema rockpaperscissor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rockpaperscissor` DEFAULT CHARACTER SET utf8 ;
USE `rockpaperscissor` ;

-- -----------------------------------------------------
-- Table `rockpaperscissor`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockpaperscissor`.`player` (
  `Name` VARCHAR(50) NOT NULL COMMENT '',
  `Points` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Name`)  COMMENT '',
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rockpaperscissor`.`tournament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockpaperscissor`.`tournament` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `FechaHora` DATETIME NOT NULL COMMENT '',
  `First` INT(11) NOT NULL COMMENT '',
  `Second` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
